### PR TITLE
chore: update loki-stack to version 2.7.*

### PR DESCRIPTION
**Pull request by luk43**
# Description
update loki-stack to version 2.7.*

# Issues

# Changelog
https://github.com/grafana/loki/blob/main/CHANGELOG.md
loki/promtail version:
2.4.2 -> 2.6.1

improvements seemingly on all ends.
# Checklist

* [ ] This PR contains a description of the changes I'm making
* [x] I updated the version in Chart.yaml
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Review by isantospardo — APPROVED** [review]
LGTM

**Comment by hairmare** [comment]
release notes are here:

* https://grafana.com/docs/loki/latest/release-notes/v2-5/
* https://grafana.com/docs/loki/latest/release-notes/v2-6/

I haven't dug into them, but do they contain anything that might be relevant to our use cases?

**Comment by luk43** [comment]
> release notes are here:
> 
> * https://grafana.com/docs/loki/latest/release-notes/v2-5/
> * https://grafana.com/docs/loki/latest/release-notes/v2-6/
> 
> I haven't dug into them, but do they contain anything that might be relevant to our use cases?

Thanks!

Most notable changes are changes to the config `split_queries_by_interval` -parameter.
I haven't gathered any mention of that in our repos.

**Comment by eyenx** [comment]
can you bump the minor release instead of patchfix?

**Pull request closed without merging**
