### PR TITLE
chore: Update secret-store-csi-driver to 1.3.1

### PR DESCRIPTION
**Pull request by janaurka**
# Description

Bumps the version of `secret-store-csi-driver` from `1.2.4` to `1.3.1`.

Especially [`1.3.0`](https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v1.3.0) had various security fixes. No change of behavior expected.

# Checklist

* [x] This PR contains a description of the changes I'm making
* [x] I updated the version in Chart.yaml
* [x] I updated the changelog with an `artifacthub.io/changes` annotation in `Chart.yaml`, check the [example](docs/development.md#Changelog) in the documentation.
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Comment by janaurka** [comment]
hmm i forgot that `pre-commit` aborts `commits` and only my last one succeeded, which was a README update but overall commited everything. I’ll make sure the squash it an create a proper merge message... :penguin:

**Comment by hairmare** [comment]
>  I’ll make sure the squash it an create a proper merge message... penguin

no worries, we squash and merge anyways :)

**Review by hairmare — APPROVED** [review]
lgtm, we should probably have a quick chat about the big-picture csi-secrets esp. in the context of azure before we roll this out at a larger scale

**Comment by eyenx** [comment]
@janaurka rebase and merge pls

**Pull request merged**
