### PR TITLE
feat(hedgedoc): Update to 1.9.8

### PR DESCRIPTION
**Pull request by gianklug**
# Description
Updated the hedgedoc chart to the latest image version. 

See https://github.com/hedgedoc/hedgedoc/releases/tag/1.9.8 for the full changelog.

Also I switched to the new `_health` endpoint for the health probe.

# Checklist

* [x] This PR contains a description of the changes I'm making
* [x] I updated the version in Chart.yaml
* [x] I updated the changelog with an `artifacthub.io/changes` annotation in `Chart.yaml`, check the [example](docs/development.md#Changelog) in the documentation.
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Review by eyenx — APPROVED** [review]

**Review by eyenx — CHANGES_REQUESTED** [review]
Why not patchfix bump?

**Comment by gianklug** [comment]
> Why not patchfix bump?

So we only increment the feature bit if there are features in the chart vs. the application? Oops!

**Comment by eyenx** [comment]
> > Why not patchfix bump?
> 
> So we only increment the feature bit if there are features in the chart vs. the application? Oops!

Are there new features in the app? Why did they only do a patchfix bump then?

**Review by eyenx — APPROVED** [review]

**Comment by eyenx** [comment]
Hedgedoc no semver convention

**Pull request merged**
