### PR TITLE
fix(keycloak-operator): db secret indentation

### PR DESCRIPTION
**Pull request by luk43**
# Description
Includes changes/fix to render the existingKey part properly in the "db" part.

# Issues

# Checklist

* [x] This PR contains a description of the changes I'm making
* [x] I updated the version in Chart.yaml
* [x] I updated the changelog with an `artifacthub.io/changes` annotation in `Chart.yaml`, check the [example](docs/development.md#Changelog) in the documentation.
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Review by hairmare — COMMENTED** [review]
looks good so far

Is there a reason for the change in ordering of the values?

I grabbed the initial order from the upstream example/docs but fully concur that it's ordered in a weird way.

**Comment by luk43** [comment]
> looks good so far
> 
> Is there a reason for the change in ordering of the values?
> 
> I grabbed the initial order from the upstream example/docs but fully concur that it's ordered in a weird way.

At some point I removed bits of this code to see what renders and what not. and then it felt like "host, port, database" should belong together when I put back the code (it made it easier for me to understand).

**Comment by luk43** [comment]
What's up with the testing? Is there a hint on what I could do here (better)?

**Comment by tongpu** [comment]
> What's up with the testing? Is there a hint on what I could do here (better)?

Probably run `pre-commit run` before committing your changes, as the `Update helm unittests snapshots` step in the pipeline is failing.

**Comment by luk43** [comment]
> > What's up with the testing? Is there a hint on what I could do here (better)?
> 
> Probably run `pre-commit run` before committing your changes, as the `Update helm unittests snapshots` step in the pipeline is failing.

I don't have any diffs after running `pre-commit run`. I checked the checkbox for this, I already did that.
I suspect if I bump the version again it would work somehow.

**Review by hairmare — APPROVED** [review]
LGTM

**Pull request merged**
