### PR TITLE
fix imageref

### LINKED ISSUE #761: Wrong url for image
**Affected chart**
openshift backup

**Describe the bug**
ghcr.io/adfinis-sygroup/openshift-etcd-backup vs ghcr.io/adfinis/openshift-etcd-backup

**To Reproduce**
1. install the chart

**Expected behavior**
be able to pull image

**Logs**
If applicable, add logs or screenshots to help illustrate the problem.

**Affected version**
Which version of the chart were you using.

**Values**
Let us know of any specific values you have configured.

**Environment**
What version of Kubernetes from what vendor are you using. What version of Helm are you using.
* output of `kubernetes version`
* output of `helm vesion`

**Additional context**

### PR DESCRIPTION
**Pull request by davidkarlsen**
Fixes #761

### CODE REVIEW

**Comment by eyenx** [comment]
Hi @davidkarlsen 

Thank you for your contribution, very much appreciated.

Please bum the Chartversion so that we get a green CI ;-)

**Comment by eyenx** [comment]
See #763 for example. Need a patchfix version bump & `pre-commit run -a `

**Comment by davidkarlsen** [comment]
@eyenx Should be OK now!

**Review by eyenx — APPROVED** [review]

**Comment by eyenx** [comment]
Thank you so much for your contribution!

**Pull request merged**
