### PR TITLE
chore(logging-apps): update fluentBit to 0.39.0

### LINKED ISSUE #1118: Version 0.39.0 of fluentBit is available!
Hi!<br/></br>There is a new version available for fluentBit!<br/><br/>current targetRevision set: `0.21.6`<br/>new version available: `0.39.0`<br/><br/>Please consider updating the `targetRevision` with a PR in this file [values.yaml](https://github.com/adfinis/helm-charts/tree/master/charts/logging-apps/values.yaml)<br/><br/>Thanks.

### PR DESCRIPTION
**Pull request by pree**
# Description

Update fluentBit to newest version.

# Issues

fixes #1118 

# Checklist

* [x] This PR contains a description of the changes I'm making
* [x] I updated the version in Chart.yaml
* [x] I updated the changelog with an `artifacthub.io/changes` annotation in `Chart.yaml`, check the [example](docs/development.md#Changelog) in the documentation.
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Comment by hairmare** [comment]
Does this also update the underlying fluent-bit version (and are there any release notes for that)?

**Comment by pree** [comment]
> Does this also update the underlying fluent-bit version (and are there any release notes for that)?

Can you check if the current commit clears up your concerns?

**Comment by hairmare** [comment]
> Can you check if the current commit clears up your concerns?

That's a lot of version updates! Are there any big picture changes we need to be aware of?

**Comment by pree** [comment]
Haven't seen any breaking changes and tried the upgrade with no issues or modifications on the values

**Review by hairmare — APPROVED** [review]

**Pull request merged**
