### PR TITLE
feat(misc-apps): update kube-downscaler chart from 0.6.0 to 0.7.0

### PR DESCRIPTION
**Pull request by hairmare**
# Description

Fixes an issue where kube-downscaler didn't have enough rbac permissions to do keda related downscaling.

# Issues

# Checklist

* [x] This PR contains a description of the changes I'm making
* [x] I updated the version in Chart.yaml
* [x] I updated the changelog according to the `artifacthub.io/changes` annotation in the Chart.yaml. See following [example](https://github.com/adfinis/helm-charts/pull/858/files).
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Review by janaurka — APPROVED** [review]
LGTM. though i miss the `DEFAULT_UPTIME: "Mon-Fri 07:00-20:00 Europe/Berlin"` variable :(

**Comment by hairmare** [comment]
it's here :grin: 
https://github.com/deliveryhero/helm-charts/blob/3fb41d7455d563ab0403346c726b7138a4e9d689/stable/kube-downscaler/values.yaml#L64

**Comment by janaurka** [comment]
> it's here grin https://github.com/deliveryhero/helm-charts/blob/3fb41d7455d563ab0403346c726b7138a4e9d689/stable/kube-downscaler/values.yaml#L64

but not enabled by default :sob:

**Comment by eyenx** [comment]
> > it's here grin https://github.com/deliveryhero/helm-charts/blob/3fb41d7455d563ab0403346c726b7138a4e9d689/stable/kube-downscaler/values.yaml#L64
> 
> but not enabled by default :sob: 

That has been changed since version 0.6.0

**Pull request merged**
