### PR TITLE
feat: add vaultwarden chart

### PR DESCRIPTION
**Pull request by gianklug**
# Description
Added a vaultwarden chart, reimagined from https://github.com/constin/vaultwarden-helm/

# Issues

# Checklist

* [x] This PR contains a description of the changes I'm making
* [x] I updated the version in Chart.yaml
* [x] I updated the changelog according to the `artifacthub.io/changes` annotation in the Chart.yaml. See following [example](https://github.com/adfinis/helm-charts/pull/858/files).
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Comment by hairmare** [comment]
> reimagined from https://github.com/constin/vaultwarden-helm/

what does this mean? if it's a copy from there then we won't be able to accept it without proper attribution.

what's wrong with the several charts that are already on artifacthub?

**Comment by gianklug** [comment]
> > reimagined from https://github.com/constin/vaultwarden-helm/
> 
> what does this mean? if it's a copy from there then we won't be able to accept it without proper attribution.
> 
> what's wrong with the several charts that are already on artifacthub?

@eyenx told me to start off with a clean chart from `helm create` as the other codebase was outdated and didn't seem to be updated.  This helm chart implements the same approach but isn't a 1:1 copy.

The other helm charts do not work as intended and are lacking some essential things as existingSecret or even Ingress.

**Comment by eyenx** [comment]
What other charts are out there? Are they maintained?

**Comment by gianklug** [comment]
never mind, we can close this. there wasn't a good chart until 1 month ago, we should've just waited :'D

https://lab.frogg.it/captnbp/vaultwarden-helm

**Pull request closed without merging**
