### PR TITLE
chore(timed): update frontend image tag to v3.2.0

### PR DESCRIPTION
**Pull request by derrabauke**
# Description

# Issues

# Checklist

* [x] This PR contains a description of the changes I'm making
* [x] I updated the version in Chart.yaml
* [x] I updated the changelog with an `artifacthub.io/changes` annotation in `Chart.yaml`, check the [example](docs/development.md#Changelog) in the documentation.
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [ ] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Review by hairmare — APPROVED** [review]
magic :eyes: :heart_eyes:

**Comment by derrabauke** [comment]
Ahh got it myself... [building the container failed](https://github.com/adfinis/timed-frontend/actions/runs/5692698562)

**Comment by hairmare** [comment]
> @hairmare you can help me with the failing tests?

failed to pull and unpack image "ghcr.io/adfinis/timed-frontend:v3.2.0": failed to resolve reference "ghcr.io/adfinis/timed-frontend:v3.2.0": ghcr.io/adfinis/timed-frontend:v3.2.0: not found

do we need to wait on ci and then rerun?

**Review by hairmare — APPROVED** [review]
:shipit:

**Pull request merged**
