### PR TITLE
feat(security-apps): Bump vault-monitoring to 0.3.0

### PR DESCRIPTION
**Pull request by in0rdr**
Fixes:
* VaultAutopilotHealthy alert name
* More accurate alert description for 15-20 minute time ranges
* depends on: https://github.com/adfinis/helm-charts/pull/1157

### CODE REVIEW

**Comment by tongpu** [comment]
Why did you create a new PR? Shouldn't these change not be part of #1157?

**Comment by in0rdr** [comment]
I was asked to do so in https://github.com/adfinis/helm-charts/pull/1157 but I can also included it here, just let me know

**Comment by hairmare** [comment]
gtg once the chart version is bumped

**Comment by hairmare** [comment]
do we have any news here?

**Comment by in0rdr** [comment]
> do we have any news here?

follow-up in https://github.com/adfinis/helm-charts/pull/1268

**Pull request closed without merging**
