### PR TITLE
[issue 1270] Feature: disable operator templates generation

### PR DESCRIPTION
**Pull request by gwydionmv**
# Description
Included property for disabling operator templates generation, same procedure as the one already available for enabling/disabling keycloak templates.

# Issues
https://github.com/adfinis/helm-charts/issues/1270

# Checklist
* [X] This PR contains a description of the changes I'm making
* [X] I updated the version in Chart.yaml
* [X] I updated the changelog with an `artifacthub.io/changes` annotation in `Chart.yaml`, check the [example](docs/development.md#Changelog) in the documentation.
* [X] I updated applicable README.md files using  `pre-commit run`
* [X] I documented any high-level concepts I'm introducing in `docs/`
* [x] CI is currently green and this is ready for review
* [X] I am ready to test changes after they are applied and released

### CODE REVIEW

**Comment by hairmare** [comment]
Hey @gwydionmv  thanks for the PR!

The "Lint and Install" jobs is currently complaining because it's missing version bumps in the `tests/` subdir and the chart's README.md will also need to be updated with the new version + value.

The failing "pre-commit" CI job might just be pure flakiness. I'm not quite sure since we have seen it fail in a while.

The following commands should update the things I mentioned:

```bash
# update unittest snapshots
helm unittest --update-snapshot charts/keycloak-operator

# update README
pre-commit run -a
```

May i ask you to run them and push the proposed changes as well? If you run into any issues, please let us now and we can run them on your behalf.

Thanks again!

**Comment by gwydionmv** [comment]
hello @hairmare ! Thanks for your comments. I run both commands with successful output, but only the README was changed. Could you please double check if everything is ok?

**Comment by gwydionmv** [comment]
hello @hairmare ! Thanks for your comments. I run both commands with successful output, README and snapshots are now updated :D could you please doublecheck if everything is ok? 😄

**Review by hairmare — APPROVED** [review]
LGTM

**Comment by hairmare** [comment]
tysm!

**Pull request merged**
