### PR TITLE
feat(velero): bump helm chart from 4.0.2 to 5.1.0

### LINKED ISSUE #1112: Version 5.0.2 of velero is available!
Hi!<br/></br>There is a new version available for velero!<br/><br/>current targetRevision set: `4.0.2`<br/>new version available: `5.0.2`<br/><br/>Please consider updating the `targetRevision` with a PR in this file [values.yaml](https://github.com/adfinis/helm-charts/tree/master/charts/infra-apps/values.yaml)<br/><br/>Thanks.

### PR DESCRIPTION
**Pull request by vmaillot**
# Description

Update Velero to 5.1.4 Helm Chart

# Issues

Fixes #1112 

# Checklist

* [x] This PR contains a description of the changes I'm making
* [x] I updated the version in Chart.yaml
* [x] I updated the changelog with an `artifacthub.io/changes` annotation in `Chart.yaml`, check the [example](docs/development.md#Changelog) in the documentation.
* [x] I updated applicable README.md files using  `pre-commit run`
* [x] I documented any high-level concepts I'm introducing in `docs/`
* [x] CI is currently green and this is ready for review
* [x] I am ready to test changes after they are applied and released

### CODE REVIEW

**Comment by eyenx** [comment]
no breaking changes?

**Comment by vmaillot** [comment]
> no breaking changes?

nop : D i dunno why the bump that far though, they are doing weird stuff with versionning

**Comment by vmaillot** [comment]
> can u rebase this and bump it all thew way to 5.1.3?

sorry for the l8ness, bumped to `5.1.4` even!

**Review by hairmare — APPROVED** [review]
LGTM

**Pull request merged**
